import Head from "next/head";
import IntroBlock from "@/components/IntroBlock";
import { client } from "./_app";
import { getAllData } from "@/graphql/Queries";
import SkillBlock from "@/components/SkillBlock";
import CompanyBlock from "@/components/CompanyBlock";
import ProjectBlock from "@/components/ProjectBlock";
import EducationBlock from "@/components/EducationBlock";
import AboutBlock from "@/components/AboutBlock";
import PlaygroundBlock from "@/components/PlaygroundBlock";

export async function getStaticProps() {
	const { data } = await client.query({
		query: getAllData,
	});

	return {
		props: { data },
	};
}

interface IImage {
	responsiveImage?: any;
}

export interface ISkill {
	id?: string;
	name?: string;
	ratings?: number;
}

export interface IAuthor {
	description?: any;
	email?: string;
	id?: string;
	linkedin?: string;
	mobile?: number;
	name?: string;
	image?: IImage;
	portfolioStacks?: ISkill[];
	gitLink?: string;
}

export interface IProject {
	id?: string;
	name?: string;
	description?: any;
	stacks?: ISkill[];
}

export interface IEducation {
	id?: string;
	instituteName?: string;
	course?: string;
	startYear?: string;
	endYear?: number;
	grade?: number;
	location?: string;
}

export interface ICompany {
	id?: string;
	current?: boolean;
	startYear?: string;
	endYear?: string;
	role?: string;
	name?: string;
	location?: string;
}

export interface IPlayground {
	id?: string;
	name?: string;
	description?: any;
	stacks?: ISkill[];
	gitLinks?: any;
}

export interface IData {
	author?: IAuthor;
	allSkillsets?: ISkill[];
	allProjects?: IProject[];
	allEducations?: IEducation[];
	allCompanies?: ICompany[];
	allPlaygrounds?: IPlayground[];
}

interface IHomeProps {
	data?: IData;
}

export default function Home({ data }: IHomeProps) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<title>Portfolio</title>
			</Head>
			<main>
				<IntroBlock data={data?.author} />
				<SkillBlock data={data?.allSkillsets} />
				<CompanyBlock data={data?.allCompanies} />
				<ProjectBlock data={data?.allProjects} />
				<PlaygroundBlock data={data?.allPlaygrounds} />
				<EducationBlock data={data?.allEducations} />
				<AboutBlock data={data?.author} />
			</main>
		</>
	);
}
